#!/bin/bash

brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils findutils grc

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep

# Install wget with IRI support
brew install wget --enable-iri

# What else i need
brew install git hg svn
brew install imagemagick
brew install openssl

brew install caskroom/cask/brew-cask
brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package
# brew cask install --appdir="/Applications" ${apps[@]}

# Outdated and else are removed
brew cleanup
